id = "go-one-pro"
name = "Go One Pro"
version = "0.1.0"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "A theme for Zed inspired by One Pro and specifically tested with Go."
repository = "https://github.com/thedadams/go-one-pro"
